### ISSUE TITLE
Plan for v0.2

### ISSUE THREAD

**Issue by yebai** [TuringLang/AdvancedHMC.jl#64]
- [x] Consider introduce the `PhasePoint` type #17 https://github.com/TuringLang/AdvancedHMC.jl/issues/50
- [x] Update gradient function to return both value and gradient #56 
- [x] RFC `find_good_eps` #27
- [x] More robust and modular way of detecting divergence #16
- [x] Return more information for each step #59
- [x] Implement Base.show for all user side types #36
- [ ] RFC `Adapter` types #28
- [x] Instantiation of new `AbstractMetric`s #45
- [ ] Simplifying `Metric` types by using `AbstractPDMat` #34 
- [x] Adding noise to step size? #10
